#!/bin/bash
echo "Helping..."
echo ""
echo ""

echo "📚 Claude Code PM - Project Management System"
# Try .claude/VERSION first (installed location), then claude-template/VERSION (dev location)
if [[ -f ".claude/VERSION" ]]; then
  VERSION=$(cat .claude/VERSION)
elif [[ -f "claude-template/VERSION" ]]; then
  VERSION=$(cat claude-template/VERSION)
else
  VERSION="unknown"
fi
echo "Version: $VERSION"
echo "============================================="
echo ""
echo "🎯 Quick Start Workflow"
echo "  1. Author work via nahel workflows (nahel/workflows/):"
echo "     prd-new → prd-parse → epic-decompose"
echo "  2. /pm:epic-sync <name>      - Push to GitHub"
echo "  3. /pm:epic-start <name>     - Start parallel execution"
echo ""
echo "📄 PRD Commands"
echo "  /pm:prd-list           - List all PRDs"
echo "  /pm:prd-edit <name>    - Edit existing PRD"
echo "  /pm:prd-status         - Show PRD implementation status"
echo ""
echo "📚 Epic Commands"
echo "  /pm:epic-sync <name>      - Push epic and tasks to GitHub"
echo "  /pm:epic-oneshot <name>   - Decompose and sync in one command"
echo "  /pm:epic-list             - List all epics"
echo "  /pm:epic-show <name>      - Display epic and its tasks"
echo "  /pm:epic-status [name]    - Show epic progress"
echo "  /pm:epic-close <name>     - Mark epic as complete"
echo "  /pm:epic-edit <name>      - Edit epic details"
echo "  /pm:epic-refresh <name>   - Update epic progress from tasks"
echo "  /pm:epic-start <name>     - Launch parallel agent execution"
echo ""
echo "📝 Issue Commands"
echo "  /pm:issue-show <num>      - Display issue and sub-issues"
echo "  /pm:issue-status <num>    - Check issue status"
echo "  /pm:issue-start <num>     - Begin work with specialized agent"
echo "  /pm:issue-sync <num>      - Push updates to GitHub"
echo "  /pm:issue-close <num>     - Mark issue as complete"
echo "  /pm:issue-reopen <num>    - Reopen closed issue"
echo "  /pm:issue-edit <num>      - Edit issue details"
echo "  /pm:issue-analyze <num>   - Analyze for parallel work streams"
echo ""
echo "🔄 Workflow Commands"
echo "  /pm:next               - Show next priority tasks"
echo "  /pm:status             - Overall project dashboard"
echo "  /pm:standup            - Daily standup report"
echo "  /pm:blocked            - Show blocked tasks"
echo "  /pm:in-progress        - List work in progress"
echo ""
echo "🔗 Sync Commands"
echo "  /pm:sync               - Full bidirectional sync with GitHub"
echo "  /pm:import <issue>     - Import existing GitHub issues"
echo ""
echo "🔧 Maintenance Commands"
echo "  /pm:validate           - Check system integrity"
echo "  /pm:clean              - Archive completed work"
echo "  /pm:search <query>     - Search across all content"
echo ""
echo "⚙️  Setup Commands"
echo "  /pm:init               - Install dependencies and configure GitHub"
echo "  /pm:help               - Show this help message"
echo ""
echo "💡 Tips"
echo "  • Use /pm:next to find available work"
echo "  • Run /pm:status for quick overview"
echo "  • Epic workflow: nahel workflows (prd-new → prd-parse → epic-decompose) → /pm:epic-sync"
echo "  • View README.md for complete documentation"

exit 0
