/**
 * AGENTS.md — the conversational entry point `nahel init` emits (PRD F2):
 * what any host agent reads on entering the repo so chat agents can drive
 * everything through pure conversation (hard constraint 5).
 *
 * The orientation content is a MARKED SECTION, not a whole file (PRD F8.3):
 * repos usually already have an AGENTS.md, and silently skipping it left
 * non-Claude agents unable to discover nahel at all. Everything between the
 * two markers is generator-owned and regenerated on every `nahel init`;
 * everything outside them is the human's and is preserved byte for byte.
 * This module is pure string work — it imports nothing and touches no fs.
 */

export const AGENTS_SECTION_BEGIN = "<!-- nahel:begin orientation -->";
export const AGENTS_SECTION_END = "<!-- nahel:end orientation -->";

/** The owned section, markers included, without a trailing newline. */
export const AGENTS_SECTION_BODY = `${AGENTS_SECTION_BEGIN}
<!-- Generated by \`nahel init\`. Edit OUTSIDE this block: everything between
     the markers is regenerated, everything outside is preserved. -->

## Working with Nahel in this repository

This project is managed with Nahel: durable, tool-agnostic project state under \`nahel/\`, written only by the \`nahel\` CLI.

### Start here

1. Run \`nahel brief\` — the onboarding pack: goal, hard constraints, knowledge pointers, current item statuses, recent activity. Act on the brief, not on repo archaeology.
2. Read \`PRODUCT.md\` (the constitution — human-owned; never edit it autonomously) and \`CONTEXT.md\` (the glossary — its terms are normative).

### Rules of the road

- **Identify yourself first.** Agents MUST set \`NAHEL_ACTOR=agent:<your-id>\` in the environment (example: \`NAHEL_ACTOR=agent:claude-code\`) before running ANY \`nahel\` command — every journal event then carries the true actor, and claim enforcement can tell agents from humans. Humans set nothing: the config actor entry is the human default.
- **Never hand-edit state.** Everything under \`nahel/\` (frontmatter, journals, hot state) is mutated only through \`nahel\` CLI verbs. If a change you need has no verb, that is a missing-feature bug — say so instead of editing files.
- **Record what happens.** Log significant events with \`nahel log\` as you work; CLI mutations journal themselves automatically.
- **Check before acting.** \`nahel status\` shows the work-item tree, \`nahel progress\` the timeline, \`nahel validate\` confirms state integrity.
- **Respect claims.** An item with \`claimed_by\` set is in human hands; the CLI refuses agent mutations on it (and its subtree) until \`nahel handback\`.
- **Everything is conversational.** Every workflow can be driven through pure conversation — slash commands are conveniences, never the only door. The canonical procedures live in \`nahel/workflows/*.md\`; \`nahel install --agent <your-agent>\` generates slash-command shims that just load them.
${AGENTS_SECTION_END}`;

/** File a fresh AGENTS.md starts from — the title line is the human's from birth. */
const AGENTS_SEED = "# AGENTS.md — how to work in this repository\n";

/** What `mergeAgentsSection` did (or would do) to the file. */
export type AgentsMergeOutcome = "created" | "merged" | "unchanged";

export interface AgentsMerge {
  /** The full file content to write. */
  content: string;
  outcome: AgentsMergeOutcome;
}

/**
 * Merge the owned orientation section into an AGENTS.md (`null` = no file
 * yet). Appended when the file has no markers, replaced in place when it
 * does — so the section appears exactly once and re-running is byte-identical.
 * Markers that do not form exactly one well-ordered pair are ambiguous:
 * merging would risk mangling the human's file, so this throws and the caller
 * leaves the file alone.
 */
export function mergeAgentsSection(existing: string | null): AgentsMerge {
  const before = existing ?? AGENTS_SEED;
  const begin = before.indexOf(AGENTS_SECTION_BEGIN);
  const end = before.indexOf(AGENTS_SECTION_END);

  let content: string;
  if (begin === -1 && end === -1) {
    // No section yet: append it, keeping every existing byte in front of it
    // and exactly one blank line between the two.
    const separator = before.endsWith("\n\n") ? "" : before.endsWith("\n") ? "\n" : "\n\n";
    content = `${before}${separator}${AGENTS_SECTION_BODY}\n`;
  } else if (
    begin === -1 ||
    end < begin ||
    before.indexOf(AGENTS_SECTION_BEGIN, begin + 1) !== -1 ||
    before.indexOf(AGENTS_SECTION_END, end + 1) !== -1
  ) {
    throw new Error(
      `AGENTS.md nahel section markers are malformed — expected exactly one ${AGENTS_SECTION_BEGIN} … ${AGENTS_SECTION_END} pair`,
    );
  } else {
    content =
      before.slice(0, begin) + AGENTS_SECTION_BODY + before.slice(end + AGENTS_SECTION_END.length);
  }

  if (existing === null) return { content, outcome: "created" };
  return { content, outcome: content === existing ? "unchanged" : "merged" };
}
