import { join } from "node:path";
import { serializeFrontmatter } from "../store/frontmatter";
import type { WorkflowDoc } from "./workflow";

/**
 * Agent target lookup table (PRD F10, ADR-0005): each entry knows where an
 * agent's command shims live and how to render one. Adding an agent is one
 * additive table entry — nothing else changes. This module is PURE (path math
 * and string rendering); the install command owns the I/O via the store.
 *
 * A shim is a generated 3-liner (roadmap locked decision 3): its whole job is
 * "load canonical workflow X". All procedure logic stays in the canonical doc.
 */

export interface AgentTarget {
  /** Repo-relative directory the agent's shims are generated into. */
  shimDir(prefix: string): string;
  /** Render the complete shim file for one workflow doc (deterministic). */
  renderShim(workflow: WorkflowDoc): string;
}

/** Render the Claude Code shim: command frontmatter + the 3-line body. */
function renderClaudeShim(workflow: WorkflowDoc): string {
  const { name, description, args } = workflow.frontmatter;
  const frontmatter: Record<string, unknown> = { description };
  if (args !== "") frontmatter["argument-hint"] = args;
  const body = [
    "",
    `This command is a generated shim: the procedure lives in the canonical workflow \`${workflow.path}\`.`,
    "Read that workflow document in full and follow it exactly, with arguments: $ARGUMENTS",
    `Do not edit this file — regenerate it with \`nahel install --agent claude\` (workflow: ${name}).`,
    "",
  ].join("\n");
  return serializeFrontmatter(frontmatter, body);
}

export const AGENT_TARGETS: Record<string, AgentTarget> = {
  claude: {
    shimDir: (prefix) => join(".claude", "commands", prefix),
    renderShim: renderClaudeShim,
  },
};

/** The agents `nahel install` can target, sorted for stable error messages. */
export const KNOWN_AGENTS: readonly string[] = Object.keys(AGENT_TARGETS).sort();
