import { join } from "node:path";
import { serializeFrontmatter } from "../store/frontmatter";
import type { WorkflowDoc } from "./workflow";

/**
 * Agent target lookup table (PRD F10, ADR-0005): each entry knows where an
 * agent's command shims live — under the repo or under the user's home, and
 * how much of that directory the generator owns — and how to render one.
 * Adding an agent is one additive table entry; nothing else changes. This
 * module is PURE (path math and string rendering); the install command owns
 * the I/O via the store.
 *
 * A shim is a generated 3-liner (roadmap locked decision 3): its whole job is
 * "load canonical workflow X". All procedure logic stays in the canonical doc.
 */

/** What an agent's shim directory is relative to. */
export type ShimRoot = "repo" | "home";

export interface AgentTarget {
  /** Whether `shimDir` hangs off the repo root or the user's home directory. */
  root: ShimRoot;
  /** Directory (relative to `root`) the agent's shims are generated into. */
  shimDir(prefix: string): string;
  /**
   * File-name prefix for shims inside `shimDir`, and with it the generator's
   * ownership scope: `""` means the whole directory is generator-owned (it
   * exists only for these shims), a non-empty prefix means the directory is
   * shared with the agent's own files and only that name namespace is owned —
   * regeneration prunes inside the namespace and never outside it.
   */
  filePrefix(prefix: string): string;
  /** Render the complete shim file for one workflow doc (deterministic). */
  renderShim(workflow: WorkflowDoc): string;
}

/**
 * Render a shim: command frontmatter + the 3-line body. Claude Code commands
 * and codex custom prompts take the same two frontmatter keys (`description`,
 * `argument-hint`) and the same `$ARGUMENTS` expansion, so one renderer serves
 * both — only the regenerate pointer names the agent it belongs to.
 */
function renderMarkdownShim(agent: string, workflow: WorkflowDoc): string {
  const { name, description, args } = workflow.frontmatter;
  const frontmatter: Record<string, unknown> = { description };
  if (args !== "") frontmatter["argument-hint"] = args;
  const body = [
    "",
    `This command is a generated shim: the procedure lives in the canonical workflow \`${workflow.path}\`.`,
    "Read that workflow document in full and follow it exactly, with arguments: $ARGUMENTS",
    `Do not edit this file — regenerate it with \`nahel install --agent ${agent}\` (workflow: ${name}).`,
    "",
  ].join("\n");
  return serializeFrontmatter(frontmatter, body);
}

export const AGENT_TARGETS: Record<string, AgentTarget> = {
  claude: {
    root: "repo",
    shimDir: (prefix) => join(".claude", "commands", prefix),
    filePrefix: () => "",
    renderShim: (workflow) => renderMarkdownShim("claude", workflow),
  },
  /**
   * Codex loads custom prompts from `$CODEX_HOME/prompts` only (default
   * `~/.codex/prompts`), scanning top-level markdown files and no
   * subdirectories — repo-level `.codex/prompts` is an open request upstream,
   * not a feature (openai/codex issues #4734, #9848). So the target is
   * home-rooted, flat, and the prefix becomes a file-name namespace:
   * `~/.codex/prompts/nd-brief.md` → `/prompts:nd-brief`. That directory
   * belongs to the user, so only the `nd-` namespace is generator-owned.
   */
  codex: {
    root: "home",
    shimDir: () => join(".codex", "prompts"),
    filePrefix: (prefix) => `${prefix}-`,
    renderShim: (workflow) => renderMarkdownShim("codex", workflow),
  },
};

/** The agents `nahel install` can target, sorted for stable error messages. */
export const KNOWN_AGENTS: readonly string[] = Object.keys(AGENT_TARGETS).sort();
